// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: t1-tunnel.proto

package lbos_t1_tunnel

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TunnelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HcTunDestIP string `protobuf:"bytes,1,opt,name=hcTunDestIP,proto3" json:"hcTunDestIP,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t1_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_t1_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_t1_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelData) GetHcTunDestIP() string {
	if x != nil {
		return x.HcTunDestIP
	}
	return ""
}

func (x *TunnelData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTunnelRuntimeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tunnels map[string]int32 `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Id      string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTunnelRuntimeData) Reset() {
	*x = GetTunnelRuntimeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t1_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTunnelRuntimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRuntimeData) ProtoMessage() {}

func (x *GetTunnelRuntimeData) ProtoReflect() protoreflect.Message {
	mi := &file_t1_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRuntimeData.ProtoReflect.Descriptor instead.
func (*GetTunnelRuntimeData) Descriptor() ([]byte, []int) {
	return file_t1_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *GetTunnelRuntimeData) GetTunnels() map[string]int32 {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *GetTunnelRuntimeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmptyTunnelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EmptyTunnelData) Reset() {
	*x = EmptyTunnelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t1_tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyTunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyTunnelData) ProtoMessage() {}

func (x *EmptyTunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_t1_tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyTunnelData.ProtoReflect.Descriptor instead.
func (*EmptyTunnelData) Descriptor() ([]byte, []int) {
	return file_t1_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *EmptyTunnelData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_t1_tunnel_proto protoreflect.FileDescriptor

var file_t1_tunnel_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x31, 0x2d, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x22, 0x3e, 0x0a, 0x0a, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x68, 0x63, 0x54, 0x75, 0x6e, 0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x63, 0x54, 0x75, 0x6e, 0x44, 0x65, 0x73, 0x74, 0x49,
	0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0xaf, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4b, 0x0a, 0x07, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x6c, 0x62,
	0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x3a, 0x0a, 0x0c, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x21, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x89, 0x02, 0x0a, 0x0f, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74,
	0x31, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x1f, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31,
	0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x1f, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x2e, 0x6c, 0x62, 0x6f, 0x73,
	0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x24, 0x2e, 0x6c, 0x62, 0x6f,
	0x73, 0x2e, 0x74, 0x31, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_t1_tunnel_proto_rawDescOnce sync.Once
	file_t1_tunnel_proto_rawDescData = file_t1_tunnel_proto_rawDesc
)

func file_t1_tunnel_proto_rawDescGZIP() []byte {
	file_t1_tunnel_proto_rawDescOnce.Do(func() {
		file_t1_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_t1_tunnel_proto_rawDescData)
	})
	return file_t1_tunnel_proto_rawDescData
}

var file_t1_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_t1_tunnel_proto_goTypes = []interface{}{
	(*TunnelData)(nil),           // 0: lbos.t1.tunnel.TunnelData
	(*GetTunnelRuntimeData)(nil), // 1: lbos.t1.tunnel.GetTunnelRuntimeData
	(*EmptyTunnelData)(nil),      // 2: lbos.t1.tunnel.EmptyTunnelData
	nil,                          // 3: lbos.t1.tunnel.GetTunnelRuntimeData.TunnelsEntry
}
var file_t1_tunnel_proto_depIdxs = []int32{
	3, // 0: lbos.t1.tunnel.GetTunnelRuntimeData.tunnels:type_name -> lbos.t1.tunnel.GetTunnelRuntimeData.TunnelsEntry
	0, // 1: lbos.t1.tunnel.TunnelGetWorker.AddTunnel:input_type -> lbos.t1.tunnel.TunnelData
	0, // 2: lbos.t1.tunnel.TunnelGetWorker.RemoveTunnel:input_type -> lbos.t1.tunnel.TunnelData
	2, // 3: lbos.t1.tunnel.TunnelGetWorker.GetTunnelRuntime:input_type -> lbos.t1.tunnel.EmptyTunnelData
	2, // 4: lbos.t1.tunnel.TunnelGetWorker.AddTunnel:output_type -> lbos.t1.tunnel.EmptyTunnelData
	2, // 5: lbos.t1.tunnel.TunnelGetWorker.RemoveTunnel:output_type -> lbos.t1.tunnel.EmptyTunnelData
	1, // 6: lbos.t1.tunnel.TunnelGetWorker.GetTunnelRuntime:output_type -> lbos.t1.tunnel.GetTunnelRuntimeData
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_t1_tunnel_proto_init() }
func file_t1_tunnel_proto_init() {
	if File_t1_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_t1_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t1_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTunnelRuntimeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t1_tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyTunnelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_t1_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_t1_tunnel_proto_goTypes,
		DependencyIndexes: file_t1_tunnel_proto_depIdxs,
		MessageInfos:      file_t1_tunnel_proto_msgTypes,
	}.Build()
	File_t1_tunnel_proto = out.File
	file_t1_tunnel_proto_rawDesc = nil
	file_t1_tunnel_proto_goTypes = nil
	file_t1_tunnel_proto_depIdxs = nil
}
