// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lbos_t1_orch

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SendRuntimeClient is the client API for SendRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendRuntimeClient interface {
	SendDummyRuntime(ctx context.Context, in *SendDummyRuntimeData, opts ...grpc.CallOption) (*EmptySendDummyData, error)
	SendIpRuleRuntime(ctx context.Context, in *SendIpRuleRuntimeData, opts ...grpc.CallOption) (*EmptySendIpRuleData, error)
}

type sendRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewSendRuntimeClient(cc grpc.ClientConnInterface) SendRuntimeClient {
	return &sendRuntimeClient{cc}
}

func (c *sendRuntimeClient) SendDummyRuntime(ctx context.Context, in *SendDummyRuntimeData, opts ...grpc.CallOption) (*EmptySendDummyData, error) {
	out := new(EmptySendDummyData)
	err := c.cc.Invoke(ctx, "/lbos.t1.orch.SendRuntime/SendDummyRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sendRuntimeClient) SendIpRuleRuntime(ctx context.Context, in *SendIpRuleRuntimeData, opts ...grpc.CallOption) (*EmptySendIpRuleData, error) {
	out := new(EmptySendIpRuleData)
	err := c.cc.Invoke(ctx, "/lbos.t1.orch.SendRuntime/SendIpRuleRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendRuntimeServer is the server API for SendRuntime service.
// All implementations must embed UnimplementedSendRuntimeServer
// for forward compatibility
type SendRuntimeServer interface {
	SendDummyRuntime(context.Context, *SendDummyRuntimeData) (*EmptySendDummyData, error)
	SendIpRuleRuntime(context.Context, *SendIpRuleRuntimeData) (*EmptySendIpRuleData, error)
	mustEmbedUnimplementedSendRuntimeServer()
}

// UnimplementedSendRuntimeServer must be embedded to have forward compatible implementations.
type UnimplementedSendRuntimeServer struct {
}

func (UnimplementedSendRuntimeServer) SendDummyRuntime(context.Context, *SendDummyRuntimeData) (*EmptySendDummyData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDummyRuntime not implemented")
}
func (UnimplementedSendRuntimeServer) SendIpRuleRuntime(context.Context, *SendIpRuleRuntimeData) (*EmptySendIpRuleData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIpRuleRuntime not implemented")
}
func (UnimplementedSendRuntimeServer) mustEmbedUnimplementedSendRuntimeServer() {}

// UnsafeSendRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendRuntimeServer will
// result in compilation errors.
type UnsafeSendRuntimeServer interface {
	mustEmbedUnimplementedSendRuntimeServer()
}

func RegisterSendRuntimeServer(s *grpc.Server, srv SendRuntimeServer) {
	s.RegisterService(&_SendRuntime_serviceDesc, srv)
}

func _SendRuntime_SendDummyRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendDummyRuntimeData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendRuntimeServer).SendDummyRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.orch.SendRuntime/SendDummyRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendRuntimeServer).SendDummyRuntime(ctx, req.(*SendDummyRuntimeData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SendRuntime_SendIpRuleRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendIpRuleRuntimeData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendRuntimeServer).SendIpRuleRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.orch.SendRuntime/SendIpRuleRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendRuntimeServer).SendIpRuleRuntime(ctx, req.(*SendIpRuleRuntimeData))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendRuntime_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lbos.t1.orch.SendRuntime",
	HandlerType: (*SendRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDummyRuntime",
			Handler:    _SendRuntime_SendDummyRuntime_Handler,
		},
		{
			MethodName: "SendIpRuleRuntime",
			Handler:    _SendRuntime_SendIpRuleRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "t1-orch.proto",
}
