// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: route.proto

package lbos_t1_route

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RouteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HcDestIP         string `protobuf:"bytes,1,opt,name=hcDestIP,proto3" json:"hcDestIP,omitempty"`
	HcTunDestIP      string `protobuf:"bytes,2,opt,name=hcTunDestIP,proto3" json:"hcTunDestIP,omitempty"`
	NeedRemoveTunnel bool   `protobuf:"varint,3,opt,name=needRemoveTunnel,proto3" json:"needRemoveTunnel,omitempty"`
	Id               string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RouteData) Reset() {
	*x = RouteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteData) ProtoMessage() {}

func (x *RouteData) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteData.ProtoReflect.Descriptor instead.
func (*RouteData) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0}
}

func (x *RouteData) GetHcDestIP() string {
	if x != nil {
		return x.HcDestIP
	}
	return ""
}

func (x *RouteData) GetHcTunDestIP() string {
	if x != nil {
		return x.HcTunDestIP
	}
	return ""
}

func (x *RouteData) GetNeedRemoveTunnel() bool {
	if x != nil {
		return x.NeedRemoveTunnel
	}
	return false
}

func (x *RouteData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllRoutesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteData []string `protobuf:"bytes,1,rep,name=routeData,proto3" json:"routeData,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAllRoutesData) Reset() {
	*x = GetAllRoutesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoutesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoutesData) ProtoMessage() {}

func (x *GetAllRoutesData) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoutesData.ProtoReflect.Descriptor instead.
func (*GetAllRoutesData) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRoutesData) GetRouteData() []string {
	if x != nil {
		return x.RouteData
	}
	return nil
}

func (x *GetAllRoutesData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmptyRouteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EmptyRouteData) Reset() {
	*x = EmptyRouteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRouteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRouteData) ProtoMessage() {}

func (x *EmptyRouteData) ProtoReflect() protoreflect.Message {
	mi := &file_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRouteData.ProtoReflect.Descriptor instead.
func (*EmptyRouteData) Descriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{2}
}

func (x *EmptyRouteData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_route_proto protoreflect.FileDescriptor

var file_route_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c,
	0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x85, 0x01, 0x0a,
	0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x63,
	0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x63,
	0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x63, 0x54, 0x75, 0x6e, 0x44,
	0x65, 0x73, 0x74, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x63, 0x54,
	0x75, 0x6e, 0x44, 0x65, 0x73, 0x74, 0x49, 0x50, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x10, 0x6e, 0x65, 0x65, 0x64, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xfc, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x08, 0x41,
	0x64, 0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74,
	0x31, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x1d, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1d, 0x2e, 0x6c, 0x62,
	0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x1f, 0x2e, 0x6c, 0x62, 0x6f, 0x73, 0x2e, 0x74, 0x31, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_route_proto_rawDescOnce sync.Once
	file_route_proto_rawDescData = file_route_proto_rawDesc
)

func file_route_proto_rawDescGZIP() []byte {
	file_route_proto_rawDescOnce.Do(func() {
		file_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_proto_rawDescData)
	})
	return file_route_proto_rawDescData
}

var file_route_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_route_proto_goTypes = []interface{}{
	(*RouteData)(nil),        // 0: lbos.t1.route.RouteData
	(*GetAllRoutesData)(nil), // 1: lbos.t1.route.GetAllRoutesData
	(*EmptyRouteData)(nil),   // 2: lbos.t1.route.EmptyRouteData
}
var file_route_proto_depIdxs = []int32{
	0, // 0: lbos.t1.route.RouteGetWorker.AddRoute:input_type -> lbos.t1.route.RouteData
	0, // 1: lbos.t1.route.RouteGetWorker.RemoveRoute:input_type -> lbos.t1.route.RouteData
	2, // 2: lbos.t1.route.RouteGetWorker.GetRouteRuntimeConfig:input_type -> lbos.t1.route.EmptyRouteData
	2, // 3: lbos.t1.route.RouteGetWorker.AddRoute:output_type -> lbos.t1.route.EmptyRouteData
	2, // 4: lbos.t1.route.RouteGetWorker.RemoveRoute:output_type -> lbos.t1.route.EmptyRouteData
	1, // 5: lbos.t1.route.RouteGetWorker.GetRouteRuntimeConfig:output_type -> lbos.t1.route.GetAllRoutesData
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_route_proto_init() }
func file_route_proto_init() {
	if File_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoutesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRouteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_route_proto_goTypes,
		DependencyIndexes: file_route_proto_depIdxs,
		MessageInfos:      file_route_proto_msgTypes,
	}.Build()
	File_route_proto = out.File
	file_route_proto_rawDesc = nil
	file_route_proto_goTypes = nil
	file_route_proto_depIdxs = nil
}
