// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lbos_t1_ipvs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IPVSGetWorkerClient is the client API for IPVSGetWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPVSGetWorkerClient interface {
	NewIPVSService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error)
	AddIPVSApplicationServersForService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error)
	RemoveIPVSService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error)
	RemoveIPVSApplicationServersFromService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error)
	GetIPVSRuntime(ctx context.Context, in *EmptyGetIPVSData, opts ...grpc.CallOption) (*PbGetIPVSRawServicesData, error)
}

type iPVSGetWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewIPVSGetWorkerClient(cc grpc.ClientConnInterface) IPVSGetWorkerClient {
	return &iPVSGetWorkerClient{cc}
}

func (c *iPVSGetWorkerClient) NewIPVSService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error) {
	out := new(EmptyGetIPVSData)
	err := c.cc.Invoke(ctx, "/lbos.t1.ipvs.IPVSGetWorker/NewIPVSService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPVSGetWorkerClient) AddIPVSApplicationServersForService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error) {
	out := new(EmptyGetIPVSData)
	err := c.cc.Invoke(ctx, "/lbos.t1.ipvs.IPVSGetWorker/AddIPVSApplicationServersForService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPVSGetWorkerClient) RemoveIPVSService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error) {
	out := new(EmptyGetIPVSData)
	err := c.cc.Invoke(ctx, "/lbos.t1.ipvs.IPVSGetWorker/RemoveIPVSService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPVSGetWorkerClient) RemoveIPVSApplicationServersFromService(ctx context.Context, in *PbGetIPVSServiceData, opts ...grpc.CallOption) (*EmptyGetIPVSData, error) {
	out := new(EmptyGetIPVSData)
	err := c.cc.Invoke(ctx, "/lbos.t1.ipvs.IPVSGetWorker/RemoveIPVSApplicationServersFromService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPVSGetWorkerClient) GetIPVSRuntime(ctx context.Context, in *EmptyGetIPVSData, opts ...grpc.CallOption) (*PbGetIPVSRawServicesData, error) {
	out := new(PbGetIPVSRawServicesData)
	err := c.cc.Invoke(ctx, "/lbos.t1.ipvs.IPVSGetWorker/GetIPVSRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPVSGetWorkerServer is the server API for IPVSGetWorker service.
// All implementations must embed UnimplementedIPVSGetWorkerServer
// for forward compatibility
type IPVSGetWorkerServer interface {
	NewIPVSService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error)
	AddIPVSApplicationServersForService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error)
	RemoveIPVSService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error)
	RemoveIPVSApplicationServersFromService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error)
	GetIPVSRuntime(context.Context, *EmptyGetIPVSData) (*PbGetIPVSRawServicesData, error)
	mustEmbedUnimplementedIPVSGetWorkerServer()
}

// UnimplementedIPVSGetWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedIPVSGetWorkerServer struct {
}

func (UnimplementedIPVSGetWorkerServer) NewIPVSService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewIPVSService not implemented")
}
func (UnimplementedIPVSGetWorkerServer) AddIPVSApplicationServersForService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIPVSApplicationServersForService not implemented")
}
func (UnimplementedIPVSGetWorkerServer) RemoveIPVSService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIPVSService not implemented")
}
func (UnimplementedIPVSGetWorkerServer) RemoveIPVSApplicationServersFromService(context.Context, *PbGetIPVSServiceData) (*EmptyGetIPVSData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIPVSApplicationServersFromService not implemented")
}
func (UnimplementedIPVSGetWorkerServer) GetIPVSRuntime(context.Context, *EmptyGetIPVSData) (*PbGetIPVSRawServicesData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIPVSRuntime not implemented")
}
func (UnimplementedIPVSGetWorkerServer) mustEmbedUnimplementedIPVSGetWorkerServer() {}

// UnsafeIPVSGetWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPVSGetWorkerServer will
// result in compilation errors.
type UnsafeIPVSGetWorkerServer interface {
	mustEmbedUnimplementedIPVSGetWorkerServer()
}

func RegisterIPVSGetWorkerServer(s grpc.ServiceRegistrar, srv IPVSGetWorkerServer) {
	s.RegisterService(&IPVSGetWorker_ServiceDesc, srv)
}

func _IPVSGetWorker_NewIPVSService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PbGetIPVSServiceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPVSGetWorkerServer).NewIPVSService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.ipvs.IPVSGetWorker/NewIPVSService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPVSGetWorkerServer).NewIPVSService(ctx, req.(*PbGetIPVSServiceData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPVSGetWorker_AddIPVSApplicationServersForService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PbGetIPVSServiceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPVSGetWorkerServer).AddIPVSApplicationServersForService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.ipvs.IPVSGetWorker/AddIPVSApplicationServersForService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPVSGetWorkerServer).AddIPVSApplicationServersForService(ctx, req.(*PbGetIPVSServiceData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPVSGetWorker_RemoveIPVSService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PbGetIPVSServiceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPVSGetWorkerServer).RemoveIPVSService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.ipvs.IPVSGetWorker/RemoveIPVSService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPVSGetWorkerServer).RemoveIPVSService(ctx, req.(*PbGetIPVSServiceData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPVSGetWorker_RemoveIPVSApplicationServersFromService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PbGetIPVSServiceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPVSGetWorkerServer).RemoveIPVSApplicationServersFromService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.ipvs.IPVSGetWorker/RemoveIPVSApplicationServersFromService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPVSGetWorkerServer).RemoveIPVSApplicationServersFromService(ctx, req.(*PbGetIPVSServiceData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPVSGetWorker_GetIPVSRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyGetIPVSData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPVSGetWorkerServer).GetIPVSRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbos.t1.ipvs.IPVSGetWorker/GetIPVSRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPVSGetWorkerServer).GetIPVSRuntime(ctx, req.(*EmptyGetIPVSData))
	}
	return interceptor(ctx, in, info, handler)
}

// IPVSGetWorker_ServiceDesc is the grpc.ServiceDesc for IPVSGetWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPVSGetWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lbos.t1.ipvs.IPVSGetWorker",
	HandlerType: (*IPVSGetWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewIPVSService",
			Handler:    _IPVSGetWorker_NewIPVSService_Handler,
		},
		{
			MethodName: "AddIPVSApplicationServersForService",
			Handler:    _IPVSGetWorker_AddIPVSApplicationServersForService_Handler,
		},
		{
			MethodName: "RemoveIPVSService",
			Handler:    _IPVSGetWorker_RemoveIPVSService_Handler,
		},
		{
			MethodName: "RemoveIPVSApplicationServersFromService",
			Handler:    _IPVSGetWorker_RemoveIPVSApplicationServersFromService_Handler,
		},
		{
			MethodName: "GetIPVSRuntime",
			Handler:    _IPVSGetWorker_GetIPVSRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "t1-ipvs.proto",
}
