env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    targets:
      - linux_amd64
    main: .
    binary: "lbost1ad"

nfpms:
  -
    id: 1
    package_name: lbost1ad
    file_name_template: "lbost1ad_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: thevan4
    homepage: https://github.com/khannz/crispy-palm-tree/lbost1a-dummy
    maintainer: SDN <sdn@*.com>
    description: lbost1ad
    license: Apache-2.0
    formats:
        - rpm
    bindir: /opt/lbost1ad
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        dependencies:
          - ipvsadm
        files:
          "bundle/rpm.lbost1ad.service": "/lib/systemd/system/lbost1ad.service"
        # empty_folders:
        #   - /bootflash/lbost1ad
        scripts:
          preinstall: "bundle/rpm.preinstall.sh"
          postinstall: "bundle/rpm.postinstall.sh"
          preremove: "bundle/rpm.preremove.sh"
          postremove: "bundle/rpm.postremove.sh"

archives:
  - name_template: 'lbost1ad_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64